### ISSUE TITLE
grimblast: area selection doesn't update until cursor moved

### ISSUE THREAD

**Issue by ErrorNoInternet** [hyprwm/contrib#100]
### Program

grimblast

### Maintainers of the program

@fufexan, @Misterio77

### Bug or Regression?

Bug

### Description

If you run `grimblast copy area`, the window selection will not update until you move your cursor. Sometimes I have my hands on my keyboard/touchpad and I want to screenshot a window without dragging across the touchpad first.

### How to reproduce

1. `grimblast copy area` or `grimblast save area -`
2. Don't move mouse

### Hyprland crash reports, program logs, images, videos

https://github.com/hyprwm/contrib/assets/61157623/dac3264c-ea85-44a7-a1fa-88cb8cfffa2d

**Comment by fufexan** [comment]
Weird, in my case it directly selects the window under the cursor without moving it.

**Comment by ErrorNoInternet** [comment]
Ah, I think it happens when you have multiple monitors. slurp seems to be focusing on some window on the first monitor instead of the current one.

**Comment by ErrorNoInternet** [comment]
slurp thinks my mouse is at -4000x for some reason, which makes it focus on the left-most monitor. Might be a Hyprland bug. Wrote a patch for slurp: [patch.txt](https://github.com/hyprwm/contrib/files/15063252/patch.txt), but I'm not sure how this will react with different monitor setups so I'm not gonna upstream this until I find out what the actual problem is.

Closing as it is a slurp/Hyprland issue.
