### ISSUE TITLE
Grimblast takes 2 times for a simple screen capture

### ISSUE THREAD

**Issue by mhiuuu** [hyprwm/contrib#102]
### Program

grimblast

### Maintainers of the program

@fufexan @Misterio77

### Bug or Regression?

Bug

### Description

Grimblast tends to freeze my screen of I try to use the same command thru bindings but **not when using terminal!**!! (I still able to open/close windows, change workspace but nothing more than that, no typing, no cursor). Like I have to use grimblast 2 times in order for it to work properly. Slurp works fine too

### How to reproduce

Put a binding config in `hyprland.conf`:
`bind = $mainMod, S, exec, grimblast copy area`
then use it to capture screen

### Hyprland crash reports, program logs, images, videos

```
The Grimblast log:
   1   │ Checking if required tools are installed. If something is missing, install it to your system a
       │ nd make it available in PATH...
   2   │    grim: OK
   3   │    slurp: OK
   4   │    hyprctl: OK
   5   │    hyprpicker: OK
   6   │    wl-copy: OK
   7   │    jq: OK
   8   │    notify-send: OK
```

This is the demonstration

https://github.com/hyprwm/contrib/assets/95751244/e6b47426-e764-4c07-a799-2b566f78f4d8

 video

**Comment by Noname672** [comment]
I had the same problem and it took me 2 hours to realize that $mainMod S is bound to togglespecialworkspace magic by default.

**Comment by mhiuuu** [comment]
Is that the new bug because I used it normally few months ago on the older version? Btw thank you so much I guess Im gonna close the issue now
