### ISSUE TITLE
bug: `grimblast save screen active -` prints out "screen"

### ISSUE THREAD

**Issue by Ciflire** [hyprwm/contrib#110]
### Program

grimblast

### Maintainers of the program

@fufexan, @Misterio77

### Bug or Regression?

Bug

### Description

`grimblast save screen active -` prints out "screen"

it doesn't actually send the image output to stdout
i don't know if it's inteded or if i'm misusign this

but `grimblast save [save|copy] screen active` works well

### How to reproduce

use the command above to reproduce the issue

**Comment by fufexan** [comment]
Looks like you want to redirect the image to stdout? In that case `grimblast save screen -` does what you want. `screen` and `active` are two distinct selectors, and can't be used with one another. See `grimblast --help` for info.
