### ISSUE TITLE
grimblast freeze option doesn't work

### ISSUE THREAD

**Issue by Gigas002** [hyprwm/contrib#118]
### Program

grimblast

### Maintainers of the program

@fufexan, @Misterio77

### Bug or Regression?

Bug

### Description

Running grimblsat with freeze option doesn't freeze screen contents

### How to reproduce

Run some video on youtube, then run `grimblast copy area --freeze` in terminal and see that video still runs, while taking a screenshot

**Comment by fufexan** [comment]
Does `grimblast check` say you're missing anything?

**Comment by Gigas002** [comment]
I was missing `hyprpicker`, but after installing it nothing changed

```
╰─ grimblast check
Checking if required tools are installed. If something is missing, install it to your system and make it available in PATH...
   grim: OK
   slurp: OK
   hyprctl: OK
   hyprpicker: OK
   wl-copy: OK
   jq: OK
   notify-send: OK
```

**Comment by fahimscirex** [comment]
Can confirm it doesn't work for me.

```
➜  ~ grimblast check
Checking if required tools are installed. If something is missing, install it to your system and make it available in PATH...
   grim: OK
   slurp: OK
   hyprctl: OK
   wl-copy: OK
   jq: OK
   notify-send: OK
```

**Comment by fufexan** [comment]
Can you try `hyprpicker -r` and see whether that freezes your screen?

**Comment by fahimscirex** [comment]
yes it does.

**Comment by fufexan** [comment]
@fahimscirex how old is your grimblast? I don't see any mention of `hyprpicker` in the `grimblast check` output.

**Comment by fahimscirex** [comment]
`grimblast-git r108.1e531dc-1` the latest source I guess, I don't know why hyprpicker isn't showing but it's indeed installed.

**Comment by fahimscirex** [comment]
i think this isn't the latest one, just tried directly from the source and it works.

**Comment by fufexan** [comment]
Yeah that's what I suspected.

**Comment by LRitzdorf** [comment]
Just encountered this as well, and my `check` output did include hyprpicker. Solved by rebuilding/reinstalling the AUR package.

**Comment by Gigas002** [comment]
`hyprpicker -r` freezes the screen for me, but yet again, `grimblast copy area --frezze` doesn't. 
Tried reinstalling the `hyprutils-git`, `hyprpicker-git` and `grimblast-git` packages, no difference

**Comment by fufexan** [comment]
@Gigas002 arguments' order matters. Run `./grimblast --freeze copy area` and it should work.

**Comment by Gigas002** [comment]
yep, works this way :)
