### ISSUE TITLE
grimblast breaks fade animation in hyprland 

### ISSUE THREAD

**Issue by DHDcc** [hyprwm/contrib#123]
### Program

grimblast

### Maintainers of the program

@fufexan, @Misterio77  

### Bug or Regression?

Bug

### Description

After using grimblast, the fade animation of apps (example: swaync, rofi) stops working in hyprland. You can make it work again by using ```hyprctl reload```. 

### How to reproduce

1. Run grimblast with the area option. (example: grimblast -n -f save area ~/test.png )
2. Open apps. (exemple: swaync, rofi)

### Hyprland crash reports, program logs, images, videos

https://github.com/user-attachments/assets/f59bfb24-6991-46a1-8b08-52ad638148d6

**Comment by fufexan** [comment]
Can you try this patch?

```diff
diff --git a/grimblast/grimblast b/grimblast/grimblast
index 27c37e1..de7a286 100755
--- a/grimblast/grimblast
+++ b/grimblast/grimblast
@@ -20,16 +20,14 @@
 
 # Check whether another instance is running
 
-
 grimblastInstanceCheck="${XDG_RUNTIME_DIR:-$XDG_CACHE_DIR:-$HOME/.cache}/grimblast.lock"
 if [ -e "$grimblastInstanceCheck" ]; then
-	exit 2
+  exit 2
 else
-	touch "$grimblastInstanceCheck"
+  touch "$grimblastInstanceCheck"
 fi
 trap "rm -f '$grimblastInstanceCheck'" EXIT
 
-
 getTargetDirectory() {
   test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
     . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
@@ -229,7 +227,7 @@ elif [ "$SUBJECT" = "area" ]; then
 
   # get fade & fadeOut animation and unset it
   # this removes the black border seen around screenshots
-  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
+  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", (if .bezier == "" then "default" else .bezier end)')"
   hyprctl keyword animation 'fadeLayers,0,1,default' >/dev/null
 
   WORKSPACES="$(hyprctl monitors -j | jq -r '[(foreach .[] as $monitor (0; if $monitor.specialWorkspace.name == "" then $monitor.activeWorkspace else $monitor.specialWorkspace end)).id]')"
```

**Comment by DHDcc** [comment]
> Can you try this patch?
> 
> ```diff
> diff --git a/grimblast/grimblast b/grimblast/grimblast
> index 27c37e1..de7a286 100755
> --- a/grimblast/grimblast
> +++ b/grimblast/grimblast
> @@ -20,16 +20,14 @@
>  
>  # Check whether another instance is running
>  
> -
>  grimblastInstanceCheck="${XDG_RUNTIME_DIR:-$XDG_CACHE_DIR:-$HOME/.cache}/grimblast.lock"
>  if [ -e "$grimblastInstanceCheck" ]; then
> -	exit 2
> +  exit 2
>  else
> -	touch "$grimblastInstanceCheck"
> +  touch "$grimblastInstanceCheck"
>  fi
>  trap "rm -f '$grimblastInstanceCheck'" EXIT
>  
> -
>  getTargetDirectory() {
>    test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
>      . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
> @@ -229,7 +227,7 @@ elif [ "$SUBJECT" = "area" ]; then
>  
>    # get fade & fadeOut animation and unset it
>    # this removes the black border seen around screenshots
> -  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
> +  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", (if .bezier == "" then "default" else .bezier end)')"
>    hyprctl keyword animation 'fadeLayers,0,1,default' >/dev/null
>  
>    WORKSPACES="$(hyprctl monitors -j | jq -r '[(foreach .[] as $monitor (0; if $monitor.specialWorkspace.name == "" then $monitor.activeWorkspace else $monitor.specialWorkspace end)).id]')"
> ```

Same issue

**Comment by fufexan** [comment]
Can you try with this?

```diff
diff --git a/grimblast/grimblast b/grimblast/grimblast
index 27c37e1..c12ace1 100755
--- a/grimblast/grimblast
+++ b/grimblast/grimblast
@@ -20,16 +20,14 @@
 
 # Check whether another instance is running
 
-
 grimblastInstanceCheck="${XDG_RUNTIME_DIR:-$XDG_CACHE_DIR:-$HOME/.cache}/grimblast.lock"
 if [ -e "$grimblastInstanceCheck" ]; then
-	exit 2
+  exit 2
 else
-	touch "$grimblastInstanceCheck"
+  touch "$grimblastInstanceCheck"
 fi
 trap "rm -f '$grimblastInstanceCheck'" EXIT
 
-
 getTargetDirectory() {
   test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
     . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
@@ -146,12 +144,6 @@ notifyError() {
   fi
 }
 
-resetFade() {
-  if [[ -n $FADELAYERS ]]; then
-    hyprctl keyword animation "$FADELAYERS" >/dev/null
-  fi
-}
-
 killHyprpicker() {
   if [ ! $HYPRPICKER_PID -eq -1 ]; then
     kill $HYPRPICKER_PID
@@ -185,7 +177,6 @@ takeScreenshot() {
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
-    resetFade
   fi
 }
 
@@ -227,10 +218,9 @@ elif [ "$SUBJECT" = "area" ]; then
     HYPRPICKER_PID=$!
   fi
 
-  # get fade & fadeOut animation and unset it
+  # disable animation for layer namespace "selection" (slurp)
   # this removes the black border seen around screenshots
-  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
-  hyprctl keyword animation 'fadeLayers,0,1,default' >/dev/null
+  hyprctl keyword layerrule "noanim,selection" >/dev/null
 
   WORKSPACES="$(hyprctl monitors -j | jq -r '[(foreach .[] as $monitor (0; if $monitor.specialWorkspace.name == "" then $monitor.activeWorkspace else $monitor.specialWorkspace end)).id]')"
   WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))')"
@@ -240,7 +230,6 @@ elif [ "$SUBJECT" = "area" ]; then
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
     killHyprpicker
-    resetFade
     exit 1
   fi
   WHAT="Area"
```

**Comment by DHDcc** [comment]
> Can you try with this?
> 
> ```diff
> diff --git a/grimblast/grimblast b/grimblast/grimblast
> index 27c37e1..c12ace1 100755
> --- a/grimblast/grimblast
> +++ b/grimblast/grimblast
> @@ -20,16 +20,14 @@
>  
>  # Check whether another instance is running
>  
> -
>  grimblastInstanceCheck="${XDG_RUNTIME_DIR:-$XDG_CACHE_DIR:-$HOME/.cache}/grimblast.lock"
>  if [ -e "$grimblastInstanceCheck" ]; then
> -	exit 2
> +  exit 2
>  else
> -	touch "$grimblastInstanceCheck"
> +  touch "$grimblastInstanceCheck"
>  fi
>  trap "rm -f '$grimblastInstanceCheck'" EXIT
>  
> -
>  getTargetDirectory() {
>    test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
>      . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
> @@ -146,12 +144,6 @@ notifyError() {
>    fi
>  }
>  
> -resetFade() {
> -  if [[ -n $FADELAYERS ]]; then
> -    hyprctl keyword animation "$FADELAYERS" >/dev/null
> -  fi
> -}
> -
>  killHyprpicker() {
>    if [ ! $HYPRPICKER_PID -eq -1 ]; then
>      kill $HYPRPICKER_PID
> @@ -185,7 +177,6 @@ takeScreenshot() {
>      grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
>    else
>      grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
> -    resetFade
>    fi
>  }
>  
> @@ -227,10 +218,9 @@ elif [ "$SUBJECT" = "area" ]; then
>      HYPRPICKER_PID=$!
>    fi
>  
> -  # get fade & fadeOut animation and unset it
> +  # disable animation for layer namespace "selection" (slurp)
>    # this removes the black border seen around screenshots
> -  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
> -  hyprctl keyword animation 'fadeLayers,0,1,default' >/dev/null
> +  hyprctl keyword layerrule "noanim,selection" >/dev/null
>  
>    WORKSPACES="$(hyprctl monitors -j | jq -r '[(foreach .[] as $monitor (0; if $monitor.specialWorkspace.name == "" then $monitor.activeWorkspace else $monitor.specialWorkspace end)).id]')"
>    WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))')"
> @@ -240,7 +230,6 @@ elif [ "$SUBJECT" = "area" ]; then
>    # Check if user exited slurp without selecting the area
>    if [ -z "$GEOM" ]; then
>      killHyprpicker
> -    resetFade
>      exit 1
>    fi
>    WHAT="Area"
> ```

This patch works
