### ISSUE TITLE
grimblast: if click is held while executing "copy area", the selection is cancelled when you let go

### ISSUE THREAD

**Issue by Leshuguita** [hyprwm/contrib#20]

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
Doesn't happen to me. Can you please share more info? `grimblast --check` maybe? Or a screen recording perhaps would help in identifying the issue.

**Comment by Leshuguita** [comment]
`grimblast check` shows everything OK.
 I press click before entering the command, then let go after moving the mouse
https://user-images.githubusercontent.com/69051056/207979955-507c753e-84c7-48cc-bff4-12fd88125938.mp4

**Comment by Leshuguita** [comment]
I'm going to close this issue, as the changes to how`areain pull request
