### ISSUE TITLE
grimblast: Allow area selection in window target

### ISSUE THREAD

**Issue by aouerfelli** [hyprwm/contrib#21]
Currently when selecting a window target, it forces you to select a window instead of allowing an area selection.

This one's pretty straightforward to get working; it can be done by removing the `-r` flag from `slurp` in [this](https://github.com/hyprwm/contrib/blob/5b21c74a3200ffdd48ed7764c7041d43c3cd5588/grimblast/grimblast#L155) line. I'm just wondering what would be the best way to include this functionality. The simplest idea I could think of is to have a combined `windowarea` target, similar to the `copysave` command.

**Comment by fufexan** [comment]
Why do that instead of selecting an area directly?

**Comment by fufexan** [comment]
I don't see how we could include both window selection and area selection. `-r` forces rectangle selections, and that wouldn't work with area selection. They have to be separate.

**Comment by aouerfelli** [comment]
Removing `-r` allows for choosing either window or area selection at the same time; clicking will select a window, while dragging will select an area instead (see the [original PR](https://github.com/emersion/slurp/pull/28)).

If you don't want to pursue this further, then feel free to close the issue. I'm totally fine with just keeping this local instead of upstreaming it.

**Comment by fufexan** [comment]
My bad, I didn't know it was possible. I'll look into it. Or perhaps you already have a working change?

**Comment by aouerfelli** [comment]
Apologies for the delay. Your PR looks good to me!
