### ISSUE TITLE
Add copy to clipboard from file - Ex. grimblast copy file inputfile.png

### ISSUE THREAD

**Issue by ChrisTitusTech** [hyprwm/contrib#24]
Add copy to clipboard from file - Ex. grimblast copy file inputfile.png

Currently we can only use area, output, active, screen for selections and I'd love to just copy some files to clipboard for ease of use.

**Comment by fufexan** [comment]
I'm sorry, I don't think I understand. So you want to copy an existing file to clipboard, or screenshot to a file and then copy it?

The latter is already how it works when you do `grimblast copysave` and one of the selectors.
The former is not grimblast's job, as it can be done with `wl-copy -t image/png <file>`.

Is this what you meant or have I missed the point?

**Comment by ChrisTitusTech** [comment]
That exactly what I needed with the `wl-copy` command. I just didn't see the grimblast syntax. I'm pretty new to wayland.
