### ISSUE TITLE
active, output error

### ISSUE THREAD

**Issue by Cruising0904** [hyprwm/contrib#25]
This is awesome tool that has many feature I really like 
![image](https://user-images.githubusercontent.com/29267295/221360701-199a6ad3-7110-4f41-8026-76835257f25a.png)

Is there something wrong with my command? I have parse error when I type output and active.

**Comment by fufexan** [comment]
Have you checked whether you have all dependencies installed? `grimblast check`.

**Comment by Cruising0904** [comment]
![image](https://user-images.githubusercontent.com/29267295/221403132-f9adb427-16a1-465c-9c47-125ab0f1f768.png)
Yes it seems so
I am running it on wayland by the way

**Comment by fufexan** [comment]
Yes, it's meant to be run on wayland. Can you add `set -ex` just below the shebang and run the script again? See what errors it outputs.

**Comment by Cruising0904** [comment]
![image](https://user-images.githubusercontent.com/29267295/221545663-1738cc78-551c-4e97-89f4-b6b870b58ab6.png)
I didn't totally understand what you are saying.. so instead of that I just run it on prompt. Is it right?

**Comment by fufexan** [comment]
No. You have to edit the script and add `set -ex` at the beginning, right after the comments and before `getTargetDirectory() {`

**Comment by Cruising0904** [comment]
> No. You have to edit the script and add `set -ex` at the beginning, right after the comments and before `getTargetDirectory() {`

sorry what is the script? Sorry for the ignorance

**Comment by fufexan** [comment]
Yeah, clone the repo or copy the script and then edit it.

**Comment by Cruising0904** [comment]
![Y0417-213427](https://user-images.githubusercontent.com/29267295/232485570-1d8bb738-6491-4a0d-bfd6-1ffd31f12a41.png)

My env if this helps

**Comment by Cruising0904** [comment]
It's the same result 
![image](https://user-images.githubusercontent.com/29267295/232486217-5c8e7353-22c8-4c99-900f-c8c1184d5712.png)

**Comment by Cruising0904** [comment]
oh... I did this in different file 
Now I have different result 
![image](https://user-images.githubusercontent.com/29267295/232486800-8b5cc850-2f79-41bc-b4bd-1c4533b89689.png)

**Comment by fufexan** [comment]
Can you paste the entire log in a gist? It's easier to read than screenshots.

**Comment by Cruising0904** [comment]
https://gist.github.com/Cruising0904/1ec3bf6ddf8989eedca6c07461f527e1

**Comment by Cruising0904** [comment]
![image](https://user-images.githubusercontent.com/29267295/232488338-d7fd3ac6-ed7d-4e46-97a7-969439df79e7.png)

hmm strange.. I use wayfire. although Hyprland is installed

**Comment by fufexan** [comment]
You cannot use grimblast on anything other than Hyprland.

**Comment by Cruising0904** [comment]
Ah.... I didn't know this Sorry
