### ISSUE TITLE
Why not using git submodules?

### ISSUE THREAD

**Issue by ArchieSW** [hyprwm/contrib#28]
It may be obvious, but I still don't get it. Why not keep submodules for third-party projects in this repository that their maintainers will add. This will make it easier for developers to maintain utilities (they won't have to do a PR for every commit). 

It will also make it easier for users to create issues, they will be distributed to the maintainer repositories. 
In general, perhaps because of this there will be a problem with licenses, I do not rummage about it.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by fufexan** [comment]
These utils usually aren't that often updated, so it makes sense to keep small scripts and such in a single repo. For bigger projects, take a look at https://github.com/hyprland-community.

**Comment by ArchieSW** [comment]
I understand your point, thanks for the explanation.

**Comment by Schievel1** [comment]
> Also because submodules are just a poor excuse for not using real packages and dependencies.

:D Seems like you have experience with that? Submodules are the worst thing that could happen for a package maintainer. (At least on Gentoo) they fit very poorly into the current package manager world. In fact they enforce that the package is going to be a live package. (What Arch calls -git package)

But for such projects like this one, maybe it isn't such a bad idea. If you ever decide for it, please set up github actions to package a tarball of all submodules as a release artifact.

**Comment by fufexan** [comment]
> :D Seems like you have experience with that?

Packaging the entire Hyprland ecosystem in Nix made me hate submodules lol.

> But for such projects like this one, maybe it isn't such a bad idea. If you ever decide for it, please set up github actions to package a tarball of all submodules as a release artifact.

I don't think we currently need it. If we ever have a sizeable amount of scripts, I'll consider it.
