### ISSUE TITLE
grimblast: support save and copy in one command

### ISSUE THREAD

**Issue by TheSunCat** [hyprwm/contrib#3]
I'm looking to switch to grimblast from my current grimshot setup. I'm looking for a way to both save the screenshot and copy it to the clipboard. I currently do this with a pretty long command that saves the screenshot to a file and then has `wl-copy` read it into the clipboard, but it sometimes fails inexplicably and it would be much nicer if it were implemented within the screenshot utility.
Would it be possible to implement such a feature in grimblast? Having it run both `save` and `copy` actions in a single command.
Thanks!

**Comment by fufexan** [comment]
Will fix it, as I also want that feature.
