### ISSUE TITLE
please make a release

### ISSUE THREAD

**Issue by Schievel1** [hyprwm/contrib#33]
I know this is just a bunch of shell scripts and package maintainers could just download a tar of the latest commit and call that a release, but the idiomatic way in distros is to have releases named after how upsteam calls them. (instead of giving them a date as version number of commit hash)

This would make things easier for maintainers and I will make a package for gentoo of this. Deal? ❤️ 
Maybe wait with the release until my PR https://github.com/hyprwm/contrib/pull/32 is merged :-)

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
Sure, I'll try to test it, merge it, and then make a release.

**Comment by fufexan** [comment]
Done in https://github.com/hyprwm/contrib/releases/tag/v0.1.

**Comment by Schievel1** [comment]
Thanks again for that. I created the package for the gentoo guru and it will be available to users soon. 	https://github.com/gentoo/guru/tree/dev/gui-wm/hyprland-contrib
