### ISSUE TITLE
scratchpad wofi support

### ISSUE THREAD

**Issue by ignamartinoli** [hyprwm/contrib#35]
Currently running `scratchpad -m 'wofi' -g` would list all applications installed.

**Comment by fufexan** [comment]
Should be `scratchpad -m 'wofi -d' -g`, since wofi isn't started in dmenu mode by default.

**Comment by fufexan** [comment]
I think putting that in a script that contains
```bash
#!/use/bin/env bash

wofi -d "$@"
```
and using `-m ./script`, could work.

**Comment by ignamartinoli** [comment]
Yea, that does work.

Why is it that I need a separate shellscript?

**Comment by fufexan** [comment]
I think the command wasn't made with the intention of using a program with arguments in there.
@niksingh710 could this be made to work with `scratchpad -m 'wofi -d'` or similar commands?

**Comment by niksingh710** [comment]
It should be working after the PR #36

**Comment by ignamartinoli** [comment]
@fufexan tried

This works:

```
bind = $Mod SHIFT, s, exec, scratchpad -m "wofi -iI -S drun -d $@" -g
```

I tried this also:

```
bind = $Mod SHIFT, s, exec, scratchpad -m "flock --nonblock /tmp/.wofi.lock -c wofi -iI -S drun -d $@" -g
```

but it doesn't work (that command is used to prevent spawning multiple instances of `wofi` if I repeatedly press `$Mod SHIFT s`.

**Comment by niksingh710** [comment]
> I tried also this:
> 
> ```
> bind = $Mod SHIFT, s, exec, scratchpad -m "flock --nonblock /tmp/.wofi.lock -c wofi -iI -S drun -d $@" -g
> ```
> 
> but it doesn't work (that command is used to prevent spawning multiple instances of `wofi` if I repeatedly press `$Mod SHIFT s`.

i will suggest to use 
 ```
bind = $Mod SHIFT, s, exec, killall -q wofi;scratchpad -m "wofi -d" -g
```
as `-m` take the command that should be in dmenu mode.
it just pipes the stdout to the command.

**Comment by fufexan** [comment]
I believe this is fixed. Closing.
