### ISSUE TITLE
Grimblast screen freeze support

### ISSUE THREAD

**Issue by PolpOnline** [hyprwm/contrib#37]
It would be nice to have a command line flag to freeze the screen while selecting the area to screenshot, this is because it is very problematic to screenshot a moving thing with the current behavior.

I don't know if this is possible with how slurp/grim work, I'm opening this issue to see if there is a way to circumvent this anyway.

**Comment by fufexan** [comment]
As far as I know, there's no such behaviour implemented. One very hacky way would be to take a fullscreen shot and display it fullscreen with something like `imv`, and then use slurp to select an area on that. However there are a few problems:
- the quality sucks
- it does not work on multiple monitors

**Comment by vaxerski** [comment]
open hyprpicker with `-r -z` before slurp, that's what I use and it works like a charm

**Comment by vaxerski** [comment]
that's what I do.

**Comment by fufexan** [comment]
I'm currently trying to implement this directly into grimblast, but pressing ESC to cancel the screenshot first cancels hyprpicker, and then you have to press it again to also cancel slurp. Any way to only require one ESC press to cancel everything?

**Comment by vaxerski** [comment]
grim ...
killall hyprpicker

**Comment by fufexan** [comment]
@vaxerski check https://github.com/hyprwm/contrib/tree/freeze, idk how to implement your idea.

**Comment by vaxerski** [comment]
kill before exit on invalid lol
