### ISSUE TITLE
Grimblast gives black output

### ISSUE THREAD

**Issue by Sohail-XD** [hyprwm/contrib#42]
Tried copying, saving the image. Also checked active/screen/output/area options. All give the same blank black image. Grimblast check also shows everything is fine. I'm currently using xdg-desktop-portal-hyprland.

**Comment by fufexan** [comment]
Are you on nvidia?

**Comment by fufexan** [comment]
Are you using any of the `hyprland-nvidia` packages? (`-bin`, `-git`)

**Comment by Sohail-XD** [comment]
> Are you using any of the `hyprland-nvidia` packages? (`-bin`, `-git`)

No, I'm just using hyprland package. I downgraded from -git package for some reason. I'll try installing 'git' package
