### ISSUE TITLE
Add Documentation for NixOS

### ISSUE THREAD

**Issue by LemonjamesD** [hyprwm/contrib#43]
Can you add NixOS documentation to know how to use the flake?

**Comment by fufexan** [comment]
Sure, but it's just adding this repo as an input and then using `inputs.hyprland-contrib.packages.${pkgs.system}.whatever`.

**Comment by fufexan** [comment]
Done in https://github.com/hyprwm/contrib/commit/fa0b667ef28c0f7e597f916eadb3f8bef48d9ef8.
