### ISSUE TITLE
grimblast: Support grim's -s option

### ISSUE THREAD

**Issue by nmccarty** [hyprwm/contrib#45]
I would like to be able to take screenshots without scaling or with a custom scale applied, so it would be nice if this tool passed through grim's `-s` option so I could control the scaling.

**Comment by fufexan** [comment]
Done in https://github.com/hyprwm/contrib/commit/7c1e9065f2c7c2a4a48239236c4c1e56e0a31775.

**Comment by nmccarty** [comment]
Thank you!
