### ISSUE TITLE
grimblast: doesn't work without the scale option

### ISSUE THREAD

**Issue by jn-sena** [hyprwm/contrib#46]
Not having the `--scale` option set gives the following error instead of the missing argument error:

![Failed to open file '' for writing: No such file or directory](https://github.com/hyprwm/contrib/assets/45771313/1e7db7e8-9569-46f0-b426-62897c611986)

It works with `--scale 1`. I think having it default to `1` instead of having to manually type it would be nice. Also, the [man page](https://github.com/hyprwm/contrib/blob/main/grimblast/grimblast.1.scd) is outdated.

Running NixOS with Home Manager using flakes.

**Comment by fufexan** [comment]
My mistake, sorry. Now it's left empty by default. I've also updated the man page. Thanks for the heads up!
