### ISSUE TITLE
try_swap_workspace: Error when checking Hyprland session

### ISSUE THREAD

**Issue by Yucklys** [hyprwm/contrib#49]
I am using NixOS and get the script by flake. However, the `try_swap_workspace` script failed with "**Make Sure Hyprland Session is running.**" notify. I install and run hyprland following its wiki and have no issue with it. So I assume there is something wrong with environment checks.

I manually disabled `pgrep -x Hyprland &>/dev/null` check  and it runs perfectly, so I just go with that. But it will be great if it can be fixed upstream so that I don't need to modify the script manually.

**Comment by Schievel1** [comment]
My computers ssd broke and I am
waiting for a new one right now.

I will have a look once I got my computer fixed. Looks like something in the environment changed or something like that

**Comment by Schievel1** [comment]
I guess we have a missing dependency in the package here. 
```
~ ➜ which pgrep                took 4s
/usr/bin/pgrep

~ ➜ equery b /usr/bin/pgrep  took 24ms
 * Searching for /usr/bin/pgrep ...
sys-process/procps-3.3.17-r2 (/usr/bin/pgrep)
```

In gentoo this is part of the base system, that is why I haven't noticed.

**Comment by fufexan** [comment]
Added here https://github.com/hyprwm/contrib/commit/bef073cff65917ba2d888aa4dc39bd9868e2b0a4. @Yucklys can you test whether this works?

**Comment by Yucklys** [comment]
> Added here [bef073c](https://github.com/hyprwm/contrib/commit/bef073cff65917ba2d888aa4dc39bd9868e2b0a4). @Yucklys can you test whether this works?

I tried this commit, but it won't work. I did some experiment latter and found that the problem is with `pgrep -x Hyprland` command.

I install Hyprland following its document for NixOS + Home-manager, and launch the session through sddm. So the actual command for Hyperland is a wrapped script called `.Hyprland-wrapp`. Calling `pgrep -x .Hyprland-wrapp` return the process id and the script run smoothly.

**Comment by Schievel1** [comment]
Home-Manager is a NixOS specific plugin, isn't it?

On gentoo we would write a patch for the script that gets applied during installation depending on a USE-flag. Maybe Nix has a similar mechanism?

**Comment by fufexan** [comment]
Sounds like we could use `pgrep Hyprland`, without the `-x`.

**Comment by Yucklys** [comment]
I just start using NixOS so I am not sure which package setting makes this change, but I guess it is related to sddm. I think using `pgrep Hyprland` advised by @fufexan is enough for my case, since no other process has the same name.

Thanks again for your help.

**Comment by Schievel1** [comment]
> Sounds like we could use `pgrep Hyprland`, without the `-x`. Afaik there aren't any complementary programs which spell `Hyprland` with uppercase H, so it should be fine.

Idk this sounds risky
