### ISSUE TITLE
The --freeze argument does not work properly

### ISSUE THREAD

**Issue by strawbberrys** [hyprwm/contrib#50]
The --freeze argument does freeze the screen, however when taking a screenshot it will not use the frozen screen, it will instead use the updated screen. This might be a limitation of ``hyprpicker -r -z``, so I'm not sure how this would be fixed unless a snapshot of the frozen screen is taken and that is used as the base of the screenshot.

``grimblast --notify --cursor --freeze copy area ``
https://streamable.com/3olo8m

**Comment by fufexan** [comment]
Seems like it. I don't know how to handle this on multiple monitors though. On one, we can simply screenshot it, display it fullscreen with imv, and move on. But on multiple it is hackier.

**Comment by nicklozon** [comment]
I agree - reading over the original [PR](https://github.com/hyprwm/contrib/pull/39) and [request](https://github.com/hyprwm/contrib/issues/37) the purpose of freezing the screen is to have the output be that of the frozen image.

I think the solution hijacks `hyprpicker` for the sole purpose of freezing the screen, however it kills the hyprpicker process BEFORE the screenshot is taken. Moving the kill command to after the screenshot is taken fixes the issue. I'll open a PR.


Sidenote: hyprpicker does not freeze the cursor on the screen, therefore using `--cursor` is pointless with `--freeze`, or using an `area` target in general.
