### ISSUE TITLE
`--freeze copy area` causes a rotated monitor to wig out

### ISSUE THREAD

**Issue by carschandler** [hyprwm/contrib#52]
Loving grimblast so far! Working exactly as expected, except that with `grimblasht --freeze copy area`, my vertical monitor rotates back to landscape and squeezes the output into that form factor. Here's my `hyprctl monitors` output:
```
Monitor DP-1 (ID 0):
	2560x1440@144.005997 at 0x500
	description: ASUSTek COMPUTER INC VG27AQ1A N8LMQS051510 (DP-1)
	make: ASUSTek COMPUTER INC
	model: VG27AQ1A
	serial: N8LMQS051510
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0

Monitor DP-2 (ID 1):
	2560x1440@143.998001 at 2560x0
	description: Dell Inc. Dell S2417DG #ASMzgbd21FTd (DP-2)
	make: Dell Inc.
	model: Dell S2417DG
	serial: #ASMzgbd21FTd
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.12
	transform: 3
	focused: yes
	dpmsStatus: 1
	vrr: 0
```

This is both what I see when the freeze is active and what grimblast captures:
![image](https://github.com/hyprwm/contrib/assets/92899389/06b8b433-9cc1-471e-86d9-8f921ffa25c6)

**Comment by fufexan** [comment]
Can you try `hyprpicker -r -z` to check whether it's a hyprpicker bug? If yes, please report this in its repo.

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprpicker/issues/35
