### ISSUE TITLE
grimblast: Black border

### ISSUE THREAD

**Issue by Incompleteusern** [hyprwm/contrib#53]
![image](https://github.com/hyprwm/contrib/assets/58920010/f8f44187-6f9c-42bf-8f32-98e6c77eb775)
Screenshots taken by grimblast have a black border.

**Comment by fufexan** [comment]
This was fixed in https://github.com/hyprwm/contrib/commit/eece565c149e13cedf02d07d248f1697db5be400, unless you're on an older version or don't use Hyprland.

**Comment by Incompleteusern** [comment]
Oh, apparently my package wasn't updated. Thanks!
