### ISSUE TITLE
grimblast : wrong requirement name (wl-copy)

### ISSUE THREAD

**Issue by Dorifor** [hyprwm/contrib#56]
https://github.com/hyprwm/contrib/blob/main/grimblast/grimblast

```makefile
...
##  - `wl-copy`: clipboard utility
...
``` 

As well as in the `grimblast check` command.

`wl-copy` doesn't seem to exist, shouldn't it be `wl-clipboard` (which have wl-copy as command) ?

**Comment by fufexan** [comment]
Tell me if 5b67181fced4fb06d26afcf9614b35765c576168 is satisfactory.

**Comment by Dorifor** [comment]
Seems right, thanks !
