### ISSUE TITLE
scratchpad: "Make Sure Hyprland Session is running" on NixOS

### ISSUE THREAD

**Issue by ErrorNoInternet** [hyprwm/contrib#71]
![image](https://github.com/hyprwm/contrib/assets/61157623/d77aa61d-8464-4a53-82b1-b1da95e08bb0)

**Comment by fufexan** [comment]
Right, we should drop the `-x`. @niksingh710 thoughts?

**Comment by niksingh710** [comment]
> Right, we should drop the `-x`. @niksingh710 thoughts?

Yep, I think dropping `-x` from the check for Hyprland will be fine.
As `Hyprland` does not need an exact match for this, it's a unique name in itself.
@fufexan can you force push this? As I am AFK or I can create a pr next weekend.

**Comment by fufexan** [comment]
Sure, I'll fix it.
