### ISSUE TITLE
scratchpad not working correctly

### ISSUE THREAD

**Issue by milesje** [hyprwm/contrib#76]
After latest update of hyprland (version 0.33.1-2) the scratchpad is not working as before. It appears to somewhat work for the first window being sent to the scratchpad, it does appear to move to a new workspace but that workspace is actually visible on the display and other workspaces are below (behind) the scratchpad workspace. 

After adding 1 window to the scratchpad no other windows will get added.
I also think wayland was also updated but I'm not 100% sure on that.

Arch Linux
wayland 1.22.0-1
wlroots 0.17.0-1
hyprland 0.33.1-2
hyprland-scratchpad-git 51.93b6aba-2

**Comment by fufexan** [comment]
@niksingh710

**Comment by niksingh710** [comment]
@milesje are you using dual monitor setup?
As I am currently on `0.32` so can't say this with certainty, but the workspace ghosting problem I have also faced when connecting or disconnecting a monitor.
As then, the special workspace somehow overlaps over the currently focused workspace, and then it all goes messy.
For that, I use a bash script that arranges workspace for me over ipc event.

**Comment by milesje** [comment]
@niksingh710 I do have a multi-monitor setup... I have an Anker docking station with 3 monitors connected so 4 monitors when you include the laptops built-in one.

**Comment by niksingh710** [comment]
> I will update the configuration to only set the one monitor and see if that changes things.

if possible try this https://github.com/niksingh710/gui-configuration/blob/master/hypr/.config/hypr/bin/monitor script that i have setted to run on every time a monitor is connected or removed.

**Comment by milesje** [comment]
@niksingh710 is script only to be run when a monitor is connected or disconnected? I of course would have to modify it to support my 4 monitor setup.... As I'm having my issue regardless if monitor(s) have been connected or disconnected. I've booted up just the laptop with no monitors connected and my hyprland config modified to only reference the 1 display and I'm still seeing the same issue.

**Comment by milesje** [comment]
OK, I modified your script to support 3 external monitors and the primary being the eDP-1 and still have the same issue after running it.

**Comment by milesje** [comment]
@niksingh710 I'm wondering if something has changed with the latest version of Hyprland with using the workspace `special:scratchpad`? I modified the scratchpad batch script to rename all references of `special:scratchpad` to `special:my_scratchpad` and now it works as expected.

**Comment by milesje** [comment]
@niksingh710 well it almost works as expected.... with my change in place it does now hide the windows in a special workspace and I can bring it back.... however I can only move 1 window into the special workspace.... When running the script in a terminal I'm getting `ok` printed out when attempting to move the second windows (terminal), but it doesn't actually move into the special workspace.

**Comment by niksingh710** [comment]
> @niksingh710 well it almost works as expected.... with my change in place it does now hide the windows in a special workspace and I can bring it back.... however I can only move 1 window into the special workspace.... When running the script in a terminal I'm getting `ok` printed out when attempting to move the second windows (terminal), but it doesn't actually move into the special workspace.

i guess i can look into that.
if changing the name from `scratchpad` to something else resolves it then i will implement a gloabal variable `HYPRLAND_SCRATCHPAD_NAME` and also a flag `-n` that will allow user to explicitly set the name of the scratchpad.

can you ensure that workspace ghosting is not an a issue if u are using some other name? in multi monitor setup also?

**Comment by milesje** [comment]
I do not have the "ghosting" issue  when using multi-monitor when changing the special workspace name.
