### ISSUE TITLE
Grimblast seems to not support 10bit displays

### ISSUE THREAD

**Issue by OtaK** [hyprwm/contrib#93]
### Program

Grimblast

### Maintainers of the program

@fufexan, @Misterio77

### Bug or Regression?

Bug

### Description

For this monitor configuration: 

```
monitor=DP-3,3840x2160@144,0x0,1.25,bitdepth,10
# Sidebar spacing
monitor=DP-3,addreserved,0,0,44,0

monitor=DP-2,1920x1080@240,3072x0,1

monitor=DP-1,1920x1080@60,4992x0,1
monitor=DP-1,transform,1 # Rotate portrait right
```

The following occurs *only* when screenshotting DP-3 (which is 10bit)

```
❯ grimblast copy area
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
```

### How to reproduce

`grimblast copy area` on a 10bit monitor

**Comment by OtaK** [comment]
It seems it's actually an issue for `grim` rather than grimblast 🤔 

```
❯ grim
[destroyed object]: error 0: Unsupported format
failed to screenshoot all outputs
```

**Comment by vaxerski** [comment]
can you please use the search feature https://github.com/hyprwm/Hyprland/issues/4735
