### ISSUE TITLE
[FR] Add desktop entry for grimblast in nix package

### ISSUE THREAD

**Issue by max-ishere** [hyprwm/contrib#97]
I was gonna PR this, but very busy atm. Can someone please add a desktop entry to grimblast's nix home-manager module? `wofi --show drun` doesnt allow running cli commands, only selecting a desktop entry.

**Comment by fufexan** [comment]
Grimblast isn't exactly runnable as-is, since it only prints the help. In order for this feature to be feasible, we'd need to have a config for grimblast.

A bind makes more sense given the scope of the program.

**Comment by max-ishere** [comment]
Yeah I think that may work better. For some of my usecases I would probably need to implement a custom command line anyway. Most of my use is either `copy area` or save to file but that would require either invoking wofi/rofi/etc or a file picker.

**Comment by max-ishere** [comment]
LibreOffice has this thing where it groups multiple entries under the same name. I was originally thinking about something like that.

![image](https://github.com/hyprwm/contrib/assets/47008271/8d315730-25ac-4e3b-8e8d-029b89bc90c1)

**Comment by max-ishere** [comment]
> In order for this feature to be feasible, we'd need to have a config for grimblast.

Also originally I was gonna have multiple entries, not just one. A config would be nice for setting a file picker command if the file name is not specified for saving.
